In [2]:
#Numpy Library

import numpy as np

a = np.array([1,3,5], dtype='int16')
b = np.array([1,2,3])
c = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
d = np.array([[[1,2,3], [4,5,6]], [[9,8,7], [6,5,4]], [[3,5,7], [6,8,10]]])

#Basics

print("a:",a)
print("b:",b)
print("c:",c)
print("d:",d)


a: [1 3 5]
b: [1 2 3]
c: [[9. 8. 7.]
 [6. 5. 4.]]
d: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 9  8  7]
  [ 6  5  4]]

 [[ 3  5  7]
  [ 6  8 10]]]


In [ ]:
#Multiplication
print("a * b =", a*b)

a * b = [ 1  6 15]


In [ ]:
#Get Dimension
print("Dimensão de a:", a.ndim)
print("Dimensão de b:", b.ndim)
print("Dimensão de c:", c.ndim)
print("Dimensão de d:", d.ndim)

Dimensão de a: 1
Dimensão de b: 1
Dimensão de c: 2
Dimensão de d: 3


In [ ]:
#Get Shape
print("Shape de a:", a.shape)
print("Shape de c:", c.shape)
print("Shape de d:", d.shape)

Shape de a: (3,)
Shape de c: (2, 3)
Shape de d: (3, 2, 3)


In [ ]:
#Get Type
print("Tipo de a:", a.dtype)
print("Tipo de b:", b.dtype)
print("Tipo de c:", c.dtype)
print("Tipo de d:", d.dtype)

Tipo de a: int16
Tipo de b: int64
Tipo de c: float64
Tipo de d: int64


In [ ]:
#Get Size
print("Tamanho de a:", a.itemsize)
print("Tamanho de b:", b.itemsize)
print("Tamanho de c:", c.itemsize)
print("Tamanho de d:", d.itemsize)

Tamanho de a: 2
Tamanho de b: 8
Tamanho de c: 8
Tamanho de d: 8


In [ ]:
#Get Total Size
print("Tamanho total de a: ", a.size * a.itemsize)
#or
print("Número de bytes a:", a.nbytes)
print("Número de bytes b:", b.nbytes)
print("Número de bytes c:", c.nbytes)

Tamanho total de a:  6
Número de bytes a: 6
Número de bytes b: 24
Número de bytes c: 48


Acessando e modificando elementos específicos

In [ ]:
#Accessing/Changing specific elements, rows, columns, etc

a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print("a:", a)
print("Shape de a:", a.shape)

a: [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Shape de a: (2, 7)


In [ ]:
#Get a specific element [r,c]
print(a[0,5])
#Other notation
print(a[1,-2])

6
13


In [ ]:
#Get a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [ ]:
#Get a specific column
print(a[:,3])

[ 4 11]


In [ ]:
#Other way [startindex:endindex:stepsize]
print(a[0, 1:6:2])

[2 4 6]


In [ ]:
#Changing numbers
a[1,5] =20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
#Changing a specific column
a[:,3]= [40,21]
print(a)

[[ 1  2  3 40  5  6  7]
 [ 8  9 10 21 12 20 14]]


In [ ]:
#3d-example
b= np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Get specific element (works outside in)
print(b[0, 1, 1])

4


In [ ]:
#Replace
b[0,1,1] = 10
print(b)

[[[ 1  2]
  [ 3 10]]

 [[ 5  6]
  [ 7  8]]]


In [ ]:
#Replace
print(b[1, :,:])
b[1, :,:] = [[11,12], [13,14]]
print(b)

[[5 6]
 [7 8]]
[[[ 1  2]
  [ 3 10]]

 [[11 12]
  [13 14]]]


In [3]:
#Initializing different types of arrays
#All 0s matrix
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
#All 1s matrix
print(np.ones((4,5), dtype='int32'))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
#Any other number
print(np.full((5,7), 99))

[[99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99]]


In [ ]:
#Any other number 
c = np.full_like(a, 9)
#other way c = np.full(a.shape, 4)
print(c)

[[9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]]


In [ ]:
#Random decimal numbers - numbers between 0 and 1
print(np.random.rand(4,2))

[[0.3448694  0.93032507]
 [0.6735952  0.4870481 ]
 [0.69909413 0.97668705]
 [0.64381789 0.37121635]]


In [ ]:
#Random decimal numbers - passing shape
print(np.random.random_sample(a.shape))

[[0.88945338 0.17761792 0.25970359 0.14272964 0.72009523 0.78628497
  0.84570762]
 [0.78991285 0.27395468 0.89360111 0.39828567 0.35285224 0.80993392
  0.85387784]]


In [ ]:
#Random integer values
print(np.random.randint(-4,21, size=(3,3)))

[[ 9  5 -2]
 [ 6  9 14]
 [ 7  6  4]]


In [ ]:
#Identity matrix
print(np.identity(12))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
matrix = np.ones((5,5))
x=np.zeros((3,3))
x[1,1]=9
matrix[1:4, 1:4]=x
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Be careful when copying arrays
a= np.array([1,2,3])
b=a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


In [ ]:
#Find the determinant
d = np.identity(3)
print(d)
det = np.linalg.det(d)
print(det)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


In [ ]:
#Linear Algebra
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

c=np.matmul(a,b)
print(c)
print(a @ b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
[[6. 6.]
 [6. 6.]]


In [ ]:
#Basic Mathematics

a=np.array([1,2,3,4])
print(a)
print(a-2)

[1 2 3 4]
[-1  0  1  2]


# **APLICAÇÃO DA BIBLIOTECA Python NUMPY**

Matrizes de Transformação

Rotação
| cos(teta)    -sin(teta)  |
|                          |
| sin(teta)     cos(teta)  |

Escala
|   sx         0  |
|                 |
|    0         sy |

1. Colete os dados do seu carro, adapte a função ler dados e a utilize.
a - Escolha o angulo de rotação e aplique uma rotação, utilizando a matriz de rotação.
b - Escolha a escala que você deseja apresentar o carro. Multiplica o array de dados pelas matriz de escala.

2. Proponha uma solução para transladar o carro de uma posição para outra.







In [15]:
# Aplicação

import turtle
import math
import time
import random

    
# Função lerDados
def lerDados(file):
  linha = tuple()
  linhas = []
  myfile = open (file)
  myline = myfile.readline ()
  while myline:
      mylist = myline.split(",")
      for i in range(len(mylist)):
          mylist[i] = float(mylist[i].strip())
          linha = tuple(mylist)
      linhas.append(linha)
      myline = myfile.readline ()
  myfile.close ()
  return linhas



#========== Veja o Exemplo abaixo ==========================================
# --------------  rotação 90 graus  ----------------

print(30 * "==")
x = [[2,3],[4,5]]
mr = [[0,-1],[1,0]]

a = np.array(x)
b = np.array(mr)
print(a)
print(b)

print(a @ b)

print(30 * "==")
# ----------  Escala  2 vezes em x e 3 vezes em y ============

z = [[2,3],[4,5]]
ms = [[2,0],[0,3]]

a = np.array(z)
b = np.array(ms)
print(a @ b)


# Nos tres exemplos voce deve apresentar o carro em cada estágio da solução



[[2 3]
 [4 5]]
[[ 0 -1]
 [ 1  0]]
[[ 3 -2]
 [ 5 -4]]
[[ 4  9]
 [ 8 15]]
